package newhaven;

enum abstract AccessibilityRole(Int) from Int to Int {
	var unknown = cast 0;
	var defaultButton = cast 1;
	var audio = cast 2;
	var video = cast 3;
	var staticText = cast 4;
	var container = cast 5;
	var panel = cast 6;
	var button = cast 7;
	var link = cast 8;
	var checkBox = cast 9;
	var radioButton = cast 10;
	var checkButton = cast 11;
	var scrollBar = cast 12;
	var scrollView = cast 13;
	var splitter = cast 14;
	var slider = cast 15;
	var spinButton = cast 16;
	var progressIndicator = cast 17;
	var textField = cast 18;
	var multilineTextField = cast 19;
	var colorPicker = cast 20;
	var table = cast 21;
	var cell = cast 22;
	var row = cast 23;
	var rowGroup = cast 24;
	var rowHeader = cast 25;
	var columnHeader = cast 26;
	var tree = cast 27;
	var treeItem = cast 28;
	var list = cast 29;
	var listItem = cast 30;
	var listBox = cast 31;
	var listBoxOption = cast 32;
	var tabBar = cast 33;
	var tab = cast 34;
	var tabPanel = cast 35;
	var menuBar = cast 36;
	var menu = cast 37;
	var menuItem = cast 38;
	var menuItemCheckBox = cast 39;
	var menuItemRadio = cast 40;
	var image = cast 41;
	var window = cast 42;
	var titleBar = cast 43;
	var dialog = cast 44;
	var tooltip = cast 45;
	public static var values = [unknown, defaultButton, audio, video, staticText, container, panel, button, link, checkBox, radioButton, checkButton, scrollBar, scrollView, splitter, slider, spinButton, progressIndicator, textField, multilineTextField, colorPicker, table, cell, row, rowGroup, rowHeader, columnHeader, tree, treeItem, list, listItem, listBox, listBoxOption, tabBar, tab, tabPanel, menuBar, menu, menuItem, menuItemCheckBox, menuItemRadio, image, window, titleBar, dialog, tooltip];

	public static function fromString(s:String):Null<Int> {
		return switch (s) {
			case "unknown": cast 0;
			case "defaultButton": cast 1;
			case "audio": cast 2;
			case "video": cast 3;
			case "staticText": cast 4;
			case "container": cast 5;
			case "panel": cast 6;
			case "button": cast 7;
			case "link": cast 8;
			case "checkBox": cast 9;
			case "radioButton": cast 10;
			case "checkButton": cast 11;
			case "scrollBar": cast 12;
			case "scrollView": cast 13;
			case "splitter": cast 14;
			case "slider": cast 15;
			case "spinButton": cast 16;
			case "progressIndicator": cast 17;
			case "textField": cast 18;
			case "multilineTextField": cast 19;
			case "colorPicker": cast 20;
			case "table": cast 21;
			case "cell": cast 22;
			case "row": cast 23;
			case "rowGroup": cast 24;
			case "rowHeader": cast 25;
			case "columnHeader": cast 26;
			case "tree": cast 27;
			case "treeItem": cast 28;
			case "list": cast 29;
			case "listItem": cast 30;
			case "listBox": cast 31;
			case "listBoxOption": cast 32;
			case "tabBar": cast 33;
			case "tab": cast 34;
			case "tabPanel": cast 35;
			case "menuBar": cast 36;
			case "menu": cast 37;
			case "menuItem": cast 38;
			case "menuItemCheckBox": cast 39;
			case "menuItemRadio": cast 40;
			case "image": cast 41;
			case "window": cast 42;
			case "titleBar": cast 43;
			case "dialog": cast 44;
			case "tooltip": cast 45;
			case _: null;
		}
	}
}
