package newhaven;

enum abstract Monitor(Int) from Int to Int {
	var timeFps = cast 0;
	var timeProcess = cast 1;
	var timePhysicsProcess = cast 2;
	var timeNavigationProcess = cast 3;
	var memoryStatic = cast 4;
	var memoryStaticMax = cast 5;
	var memoryMessageBufferMax = cast 6;
	var objectCount = cast 7;
	var objectResourceCount = cast 8;
	var objectNodeCount = cast 9;
	var objectOrphanNodeCount = cast 10;
	var renderTotalObjectsInFrame = cast 11;
	var renderTotalPrimitivesInFrame = cast 12;
	var renderTotalDrawCallsInFrame = cast 13;
	var renderVideoMemUsed = cast 14;
	var renderTextureMemUsed = cast 15;
	var renderBufferMemUsed = cast 16;
	var physics2dActiveObjects = cast 17;
	var physics2dCollisionPairs = cast 18;
	var physics2dIslandCount = cast 19;
	var physics3dActiveObjects = cast 20;
	var physics3dCollisionPairs = cast 21;
	var physics3dIslandCount = cast 22;
	var audioOutputLatency = cast 23;
	var navigationActiveMaps = cast 24;
	var navigationRegionCount = cast 25;
	var navigationAgentCount = cast 26;
	var navigationLinkCount = cast 27;
	var navigationPolygonCount = cast 28;
	var navigationEdgeCount = cast 29;
	var navigationEdgeMergeCount = cast 30;
	var navigationEdgeConnectionCount = cast 31;
	var navigationEdgeFreeCount = cast 32;
	var navigationObstacleCount = cast 33;
	var pipelineCompilationsCanvas = cast 34;
	var pipelineCompilationsMesh = cast 35;
	var pipelineCompilationsSurface = cast 36;
	var pipelineCompilationsDraw = cast 37;
	var pipelineCompilationsSpecialization = cast 38;
	var navigation2dActiveMaps = cast 39;
	var navigation2dRegionCount = cast 40;
	var navigation2dAgentCount = cast 41;
	var navigation2dLinkCount = cast 42;
	var navigation2dPolygonCount = cast 43;
	var navigation2dEdgeCount = cast 44;
	var navigation2dEdgeMergeCount = cast 45;
	var navigation2dEdgeConnectionCount = cast 46;
	var navigation2dEdgeFreeCount = cast 47;
	var navigation2dObstacleCount = cast 48;
	var navigation3dActiveMaps = cast 49;
	var navigation3dRegionCount = cast 50;
	var navigation3dAgentCount = cast 51;
	var navigation3dLinkCount = cast 52;
	var navigation3dPolygonCount = cast 53;
	var navigation3dEdgeCount = cast 54;
	var navigation3dEdgeMergeCount = cast 55;
	var navigation3dEdgeConnectionCount = cast 56;
	var navigation3dEdgeFreeCount = cast 57;
	var navigation3dObstacleCount = cast 58;
	var monitorMax = cast 59;
	public static var values = [timeFps, timeProcess, timePhysicsProcess, timeNavigationProcess, memoryStatic, memoryStaticMax, memoryMessageBufferMax, objectCount, objectResourceCount, objectNodeCount, objectOrphanNodeCount, renderTotalObjectsInFrame, renderTotalPrimitivesInFrame, renderTotalDrawCallsInFrame, renderVideoMemUsed, renderTextureMemUsed, renderBufferMemUsed, physics2dActiveObjects, physics2dCollisionPairs, physics2dIslandCount, physics3dActiveObjects, physics3dCollisionPairs, physics3dIslandCount, audioOutputLatency, navigationActiveMaps, navigationRegionCount, navigationAgentCount, navigationLinkCount, navigationPolygonCount, navigationEdgeCount, navigationEdgeMergeCount, navigationEdgeConnectionCount, navigationEdgeFreeCount, navigationObstacleCount, pipelineCompilationsCanvas, pipelineCompilationsMesh, pipelineCompilationsSurface, pipelineCompilationsDraw, pipelineCompilationsSpecialization, navigation2dActiveMaps, navigation2dRegionCount, navigation2dAgentCount, navigation2dLinkCount, navigation2dPolygonCount, navigation2dEdgeCount, navigation2dEdgeMergeCount, navigation2dEdgeConnectionCount, navigation2dEdgeFreeCount, navigation2dObstacleCount, navigation3dActiveMaps, navigation3dRegionCount, navigation3dAgentCount, navigation3dLinkCount, navigation3dPolygonCount, navigation3dEdgeCount, navigation3dEdgeMergeCount, navigation3dEdgeConnectionCount, navigation3dEdgeFreeCount, navigation3dObstacleCount, monitorMax];

	public static function fromString(s:String):Null<Int> {
		return switch (s) {
			case "timeFps": cast 0;
			case "timeProcess": cast 1;
			case "timePhysicsProcess": cast 2;
			case "timeNavigationProcess": cast 3;
			case "memoryStatic": cast 4;
			case "memoryStaticMax": cast 5;
			case "memoryMessageBufferMax": cast 6;
			case "objectCount": cast 7;
			case "objectResourceCount": cast 8;
			case "objectNodeCount": cast 9;
			case "objectOrphanNodeCount": cast 10;
			case "renderTotalObjectsInFrame": cast 11;
			case "renderTotalPrimitivesInFrame": cast 12;
			case "renderTotalDrawCallsInFrame": cast 13;
			case "renderVideoMemUsed": cast 14;
			case "renderTextureMemUsed": cast 15;
			case "renderBufferMemUsed": cast 16;
			case "physics2dActiveObjects": cast 17;
			case "physics2dCollisionPairs": cast 18;
			case "physics2dIslandCount": cast 19;
			case "physics3dActiveObjects": cast 20;
			case "physics3dCollisionPairs": cast 21;
			case "physics3dIslandCount": cast 22;
			case "audioOutputLatency": cast 23;
			case "navigationActiveMaps": cast 24;
			case "navigationRegionCount": cast 25;
			case "navigationAgentCount": cast 26;
			case "navigationLinkCount": cast 27;
			case "navigationPolygonCount": cast 28;
			case "navigationEdgeCount": cast 29;
			case "navigationEdgeMergeCount": cast 30;
			case "navigationEdgeConnectionCount": cast 31;
			case "navigationEdgeFreeCount": cast 32;
			case "navigationObstacleCount": cast 33;
			case "pipelineCompilationsCanvas": cast 34;
			case "pipelineCompilationsMesh": cast 35;
			case "pipelineCompilationsSurface": cast 36;
			case "pipelineCompilationsDraw": cast 37;
			case "pipelineCompilationsSpecialization": cast 38;
			case "navigation2dActiveMaps": cast 39;
			case "navigation2dRegionCount": cast 40;
			case "navigation2dAgentCount": cast 41;
			case "navigation2dLinkCount": cast 42;
			case "navigation2dPolygonCount": cast 43;
			case "navigation2dEdgeCount": cast 44;
			case "navigation2dEdgeMergeCount": cast 45;
			case "navigation2dEdgeConnectionCount": cast 46;
			case "navigation2dEdgeFreeCount": cast 47;
			case "navigation2dObstacleCount": cast 48;
			case "navigation3dActiveMaps": cast 49;
			case "navigation3dRegionCount": cast 50;
			case "navigation3dAgentCount": cast 51;
			case "navigation3dLinkCount": cast 52;
			case "navigation3dPolygonCount": cast 53;
			case "navigation3dEdgeCount": cast 54;
			case "navigation3dEdgeMergeCount": cast 55;
			case "navigation3dEdgeConnectionCount": cast 56;
			case "navigation3dEdgeFreeCount": cast 57;
			case "navigation3dObstacleCount": cast 58;
			case "monitorMax": cast 59;
			case _: null;
		}
	}
}
