package newhaven;

enum abstract ResponseCode(Int) from Int to Int {
	var _continue = cast 100;
	var switchingProtocols = cast 101;
	var processing = cast 102;
	var ok = cast 200;
	var created = cast 201;
	var accepted = cast 202;
	var nonAuthoritativeInformation = cast 203;
	var noContent = cast 204;
	var resetContent = cast 205;
	var partialContent = cast 206;
	var multiStatus = cast 207;
	var alreadyReported = cast 208;
	var imUsed = cast 226;
	var multipleChoices = cast 300;
	var movedPermanently = cast 301;
	var found = cast 302;
	var seeOther = cast 303;
	var notModified = cast 304;
	var useProxy = cast 305;
	var switchProxy = cast 306;
	var temporaryRedirect = cast 307;
	var permanentRedirect = cast 308;
	var badRequest = cast 400;
	var unauthorized = cast 401;
	var paymentRequired = cast 402;
	var forbidden = cast 403;
	var notFound = cast 404;
	var methodNotAllowed = cast 405;
	var notAcceptable = cast 406;
	var proxyAuthenticationRequired = cast 407;
	var requestTimeout = cast 408;
	var conflict = cast 409;
	var gone = cast 410;
	var lengthRequired = cast 411;
	var preconditionFailed = cast 412;
	var requestEntityTooLarge = cast 413;
	var requestUriTooLong = cast 414;
	var unsupportedMediaType = cast 415;
	var requestedRangeNotSatisfiable = cast 416;
	var expectationFailed = cast 417;
	var imATeapot = cast 418;
	var misdirectedRequest = cast 421;
	var unprocessableEntity = cast 422;
	var locked = cast 423;
	var failedDependency = cast 424;
	var upgradeRequired = cast 426;
	var preconditionRequired = cast 428;
	var tooManyRequests = cast 429;
	var requestHeaderFieldsTooLarge = cast 431;
	var unavailableForLegalReasons = cast 451;
	var internalServerError = cast 500;
	var notImplemented = cast 501;
	var badGateway = cast 502;
	var serviceUnavailable = cast 503;
	var gatewayTimeout = cast 504;
	var httpVersionNotSupported = cast 505;
	var variantAlsoNegotiates = cast 506;
	var insufficientStorage = cast 507;
	var loopDetected = cast 508;
	var notExtended = cast 510;
	var networkAuthRequired = cast 511;
	public static var values = [_continue, switchingProtocols, processing, ok, created, accepted, nonAuthoritativeInformation, noContent, resetContent, partialContent, multiStatus, alreadyReported, imUsed, multipleChoices, movedPermanently, found, seeOther, notModified, useProxy, switchProxy, temporaryRedirect, permanentRedirect, badRequest, unauthorized, paymentRequired, forbidden, notFound, methodNotAllowed, notAcceptable, proxyAuthenticationRequired, requestTimeout, conflict, gone, lengthRequired, preconditionFailed, requestEntityTooLarge, requestUriTooLong, unsupportedMediaType, requestedRangeNotSatisfiable, expectationFailed, imATeapot, misdirectedRequest, unprocessableEntity, locked, failedDependency, upgradeRequired, preconditionRequired, tooManyRequests, requestHeaderFieldsTooLarge, unavailableForLegalReasons, internalServerError, notImplemented, badGateway, serviceUnavailable, gatewayTimeout, httpVersionNotSupported, variantAlsoNegotiates, insufficientStorage, loopDetected, notExtended, networkAuthRequired];

	public static function fromString(s:String):Null<Int> {
		return switch (s) {
			case "_continue": cast 100;
			case "switchingProtocols": cast 101;
			case "processing": cast 102;
			case "ok": cast 200;
			case "created": cast 201;
			case "accepted": cast 202;
			case "nonAuthoritativeInformation": cast 203;
			case "noContent": cast 204;
			case "resetContent": cast 205;
			case "partialContent": cast 206;
			case "multiStatus": cast 207;
			case "alreadyReported": cast 208;
			case "imUsed": cast 226;
			case "multipleChoices": cast 300;
			case "movedPermanently": cast 301;
			case "found": cast 302;
			case "seeOther": cast 303;
			case "notModified": cast 304;
			case "useProxy": cast 305;
			case "switchProxy": cast 306;
			case "temporaryRedirect": cast 307;
			case "permanentRedirect": cast 308;
			case "badRequest": cast 400;
			case "unauthorized": cast 401;
			case "paymentRequired": cast 402;
			case "forbidden": cast 403;
			case "notFound": cast 404;
			case "methodNotAllowed": cast 405;
			case "notAcceptable": cast 406;
			case "proxyAuthenticationRequired": cast 407;
			case "requestTimeout": cast 408;
			case "conflict": cast 409;
			case "gone": cast 410;
			case "lengthRequired": cast 411;
			case "preconditionFailed": cast 412;
			case "requestEntityTooLarge": cast 413;
			case "requestUriTooLong": cast 414;
			case "unsupportedMediaType": cast 415;
			case "requestedRangeNotSatisfiable": cast 416;
			case "expectationFailed": cast 417;
			case "imATeapot": cast 418;
			case "misdirectedRequest": cast 421;
			case "unprocessableEntity": cast 422;
			case "locked": cast 423;
			case "failedDependency": cast 424;
			case "upgradeRequired": cast 426;
			case "preconditionRequired": cast 428;
			case "tooManyRequests": cast 429;
			case "requestHeaderFieldsTooLarge": cast 431;
			case "unavailableForLegalReasons": cast 451;
			case "internalServerError": cast 500;
			case "notImplemented": cast 501;
			case "badGateway": cast 502;
			case "serviceUnavailable": cast 503;
			case "gatewayTimeout": cast 504;
			case "httpVersionNotSupported": cast 505;
			case "variantAlsoNegotiates": cast 506;
			case "insufficientStorage": cast 507;
			case "loopDetected": cast 508;
			case "notExtended": cast 510;
			case "networkAuthRequired": cast 511;
			case _: null;
		}
	}
}
