package sunaba;

enum abstract BlendShapeEntry(Int) from Int to Int {
	var eyeLookOutRight = cast 0;
	var eyeLookInRight = cast 1;
	var eyeLookUpRight = cast 2;
	var eyeLookDownRight = cast 3;
	var eyeLookOutLeft = cast 4;
	var eyeLookInLeft = cast 5;
	var eyeLookUpLeft = cast 6;
	var eyeLookDownLeft = cast 7;
	var eyeClosedRight = cast 8;
	var eyeClosedLeft = cast 9;
	var eyeSquintRight = cast 10;
	var eyeSquintLeft = cast 11;
	var eyeWideRight = cast 12;
	var eyeWideLeft = cast 13;
	var eyeDilationRight = cast 14;
	var eyeDilationLeft = cast 15;
	var eyeConstrictRight = cast 16;
	var eyeConstrictLeft = cast 17;
	var browPinchRight = cast 18;
	var browPinchLeft = cast 19;
	var browLowererRight = cast 20;
	var browLowererLeft = cast 21;
	var browInnerUpRight = cast 22;
	var browInnerUpLeft = cast 23;
	var browOuterUpRight = cast 24;
	var browOuterUpLeft = cast 25;
	var noseSneerRight = cast 26;
	var noseSneerLeft = cast 27;
	var nasalDilationRight = cast 28;
	var nasalDilationLeft = cast 29;
	var nasalConstrictRight = cast 30;
	var nasalConstrictLeft = cast 31;
	var cheekSquintRight = cast 32;
	var cheekSquintLeft = cast 33;
	var cheekPuffRight = cast 34;
	var cheekPuffLeft = cast 35;
	var cheekSuckRight = cast 36;
	var cheekSuckLeft = cast 37;
	var jawOpen = cast 38;
	var mouthClosed = cast 39;
	var jawRight = cast 40;
	var jawLeft = cast 41;
	var jawForward = cast 42;
	var jawBackward = cast 43;
	var jawClench = cast 44;
	var jawMandibleRaise = cast 45;
	var lipSuckUpperRight = cast 46;
	var lipSuckUpperLeft = cast 47;
	var lipSuckLowerRight = cast 48;
	var lipSuckLowerLeft = cast 49;
	var lipSuckCornerRight = cast 50;
	var lipSuckCornerLeft = cast 51;
	var lipFunnelUpperRight = cast 52;
	var lipFunnelUpperLeft = cast 53;
	var lipFunnelLowerRight = cast 54;
	var lipFunnelLowerLeft = cast 55;
	var lipPuckerUpperRight = cast 56;
	var lipPuckerUpperLeft = cast 57;
	var lipPuckerLowerRight = cast 58;
	var lipPuckerLowerLeft = cast 59;
	var mouthUpperUpRight = cast 60;
	var mouthUpperUpLeft = cast 61;
	var mouthLowerDownRight = cast 62;
	var mouthLowerDownLeft = cast 63;
	var mouthUpperDeepenRight = cast 64;
	var mouthUpperDeepenLeft = cast 65;
	var mouthUpperRight = cast 66;
	var mouthUpperLeft = cast 67;
	var mouthLowerRight = cast 68;
	var mouthLowerLeft = cast 69;
	var mouthCornerPullRight = cast 70;
	var mouthCornerPullLeft = cast 71;
	var mouthCornerSlantRight = cast 72;
	var mouthCornerSlantLeft = cast 73;
	var mouthFrownRight = cast 74;
	var mouthFrownLeft = cast 75;
	var mouthStretchRight = cast 76;
	var mouthStretchLeft = cast 77;
	var mouthDimpleRight = cast 78;
	var mouthDimpleLeft = cast 79;
	var mouthRaiserUpper = cast 80;
	var mouthRaiserLower = cast 81;
	var mouthPressRight = cast 82;
	var mouthPressLeft = cast 83;
	var mouthTightenerRight = cast 84;
	var mouthTightenerLeft = cast 85;
	var tongueOut = cast 86;
	var tongueUp = cast 87;
	var tongueDown = cast 88;
	var tongueRight = cast 89;
	var tongueLeft = cast 90;
	var tongueRoll = cast 91;
	var tongueBlendDown = cast 92;
	var tongueCurlUp = cast 93;
	var tongueSquish = cast 94;
	var tongueFlat = cast 95;
	var tongueTwistRight = cast 96;
	var tongueTwistLeft = cast 97;
	var softPalateClose = cast 98;
	var throatSwallow = cast 99;
	var neckFlexRight = cast 100;
	var neckFlexLeft = cast 101;
	var eyeClosed = cast 102;
	var eyeWide = cast 103;
	var eyeSquint = cast 104;
	var eyeDilation = cast 105;
	var eyeConstrict = cast 106;
	var browDownRight = cast 107;
	var browDownLeft = cast 108;
	var browDown = cast 109;
	var browUpRight = cast 110;
	var browUpLeft = cast 111;
	var browUp = cast 112;
	var noseSneer = cast 113;
	var nasalDilation = cast 114;
	var nasalConstrict = cast 115;
	var cheekPuff = cast 116;
	var cheekSuck = cast 117;
	var cheekSquint = cast 118;
	var lipSuckUpper = cast 119;
	var lipSuckLower = cast 120;
	var lipSuck = cast 121;
	var lipFunnelUpper = cast 122;
	var lipFunnelLower = cast 123;
	var lipFunnel = cast 124;
	var lipPuckerUpper = cast 125;
	var lipPuckerLower = cast 126;
	var lipPucker = cast 127;
	var mouthUpperUp = cast 128;
	var mouthLowerDown = cast 129;
	var mouthOpen = cast 130;
	var mouthRight = cast 131;
	var mouthLeft = cast 132;
	var mouthSmileRight = cast 133;
	var mouthSmileLeft = cast 134;
	var mouthSmile = cast 135;
	var mouthSadRight = cast 136;
	var mouthSadLeft = cast 137;
	var mouthSad = cast 138;
	var mouthStretch = cast 139;
	var mouthDimple = cast 140;
	var mouthTightener = cast 141;
	var mouthPress = cast 142;
	var max = cast 143;
	public static var values = [eyeLookOutRight, eyeLookInRight, eyeLookUpRight, eyeLookDownRight, eyeLookOutLeft, eyeLookInLeft, eyeLookUpLeft, eyeLookDownLeft, eyeClosedRight, eyeClosedLeft, eyeSquintRight, eyeSquintLeft, eyeWideRight, eyeWideLeft, eyeDilationRight, eyeDilationLeft, eyeConstrictRight, eyeConstrictLeft, browPinchRight, browPinchLeft, browLowererRight, browLowererLeft, browInnerUpRight, browInnerUpLeft, browOuterUpRight, browOuterUpLeft, noseSneerRight, noseSneerLeft, nasalDilationRight, nasalDilationLeft, nasalConstrictRight, nasalConstrictLeft, cheekSquintRight, cheekSquintLeft, cheekPuffRight, cheekPuffLeft, cheekSuckRight, cheekSuckLeft, jawOpen, mouthClosed, jawRight, jawLeft, jawForward, jawBackward, jawClench, jawMandibleRaise, lipSuckUpperRight, lipSuckUpperLeft, lipSuckLowerRight, lipSuckLowerLeft, lipSuckCornerRight, lipSuckCornerLeft, lipFunnelUpperRight, lipFunnelUpperLeft, lipFunnelLowerRight, lipFunnelLowerLeft, lipPuckerUpperRight, lipPuckerUpperLeft, lipPuckerLowerRight, lipPuckerLowerLeft, mouthUpperUpRight, mouthUpperUpLeft, mouthLowerDownRight, mouthLowerDownLeft, mouthUpperDeepenRight, mouthUpperDeepenLeft, mouthUpperRight, mouthUpperLeft, mouthLowerRight, mouthLowerLeft, mouthCornerPullRight, mouthCornerPullLeft, mouthCornerSlantRight, mouthCornerSlantLeft, mouthFrownRight, mouthFrownLeft, mouthStretchRight, mouthStretchLeft, mouthDimpleRight, mouthDimpleLeft, mouthRaiserUpper, mouthRaiserLower, mouthPressRight, mouthPressLeft, mouthTightenerRight, mouthTightenerLeft, tongueOut, tongueUp, tongueDown, tongueRight, tongueLeft, tongueRoll, tongueBlendDown, tongueCurlUp, tongueSquish, tongueFlat, tongueTwistRight, tongueTwistLeft, softPalateClose, throatSwallow, neckFlexRight, neckFlexLeft, eyeClosed, eyeWide, eyeSquint, eyeDilation, eyeConstrict, browDownRight, browDownLeft, browDown, browUpRight, browUpLeft, browUp, noseSneer, nasalDilation, nasalConstrict, cheekPuff, cheekSuck, cheekSquint, lipSuckUpper, lipSuckLower, lipSuck, lipFunnelUpper, lipFunnelLower, lipFunnel, lipPuckerUpper, lipPuckerLower, lipPucker, mouthUpperUp, mouthLowerDown, mouthOpen, mouthRight, mouthLeft, mouthSmileRight, mouthSmileLeft, mouthSmile, mouthSadRight, mouthSadLeft, mouthSad, mouthStretch, mouthDimple, mouthTightener, mouthPress, max];

	public static function fromString(s:String):Null<Int> {
		return switch (s) {
			case "eyeLookOutRight": cast 0;
			case "eyeLookInRight": cast 1;
			case "eyeLookUpRight": cast 2;
			case "eyeLookDownRight": cast 3;
			case "eyeLookOutLeft": cast 4;
			case "eyeLookInLeft": cast 5;
			case "eyeLookUpLeft": cast 6;
			case "eyeLookDownLeft": cast 7;
			case "eyeClosedRight": cast 8;
			case "eyeClosedLeft": cast 9;
			case "eyeSquintRight": cast 10;
			case "eyeSquintLeft": cast 11;
			case "eyeWideRight": cast 12;
			case "eyeWideLeft": cast 13;
			case "eyeDilationRight": cast 14;
			case "eyeDilationLeft": cast 15;
			case "eyeConstrictRight": cast 16;
			case "eyeConstrictLeft": cast 17;
			case "browPinchRight": cast 18;
			case "browPinchLeft": cast 19;
			case "browLowererRight": cast 20;
			case "browLowererLeft": cast 21;
			case "browInnerUpRight": cast 22;
			case "browInnerUpLeft": cast 23;
			case "browOuterUpRight": cast 24;
			case "browOuterUpLeft": cast 25;
			case "noseSneerRight": cast 26;
			case "noseSneerLeft": cast 27;
			case "nasalDilationRight": cast 28;
			case "nasalDilationLeft": cast 29;
			case "nasalConstrictRight": cast 30;
			case "nasalConstrictLeft": cast 31;
			case "cheekSquintRight": cast 32;
			case "cheekSquintLeft": cast 33;
			case "cheekPuffRight": cast 34;
			case "cheekPuffLeft": cast 35;
			case "cheekSuckRight": cast 36;
			case "cheekSuckLeft": cast 37;
			case "jawOpen": cast 38;
			case "mouthClosed": cast 39;
			case "jawRight": cast 40;
			case "jawLeft": cast 41;
			case "jawForward": cast 42;
			case "jawBackward": cast 43;
			case "jawClench": cast 44;
			case "jawMandibleRaise": cast 45;
			case "lipSuckUpperRight": cast 46;
			case "lipSuckUpperLeft": cast 47;
			case "lipSuckLowerRight": cast 48;
			case "lipSuckLowerLeft": cast 49;
			case "lipSuckCornerRight": cast 50;
			case "lipSuckCornerLeft": cast 51;
			case "lipFunnelUpperRight": cast 52;
			case "lipFunnelUpperLeft": cast 53;
			case "lipFunnelLowerRight": cast 54;
			case "lipFunnelLowerLeft": cast 55;
			case "lipPuckerUpperRight": cast 56;
			case "lipPuckerUpperLeft": cast 57;
			case "lipPuckerLowerRight": cast 58;
			case "lipPuckerLowerLeft": cast 59;
			case "mouthUpperUpRight": cast 60;
			case "mouthUpperUpLeft": cast 61;
			case "mouthLowerDownRight": cast 62;
			case "mouthLowerDownLeft": cast 63;
			case "mouthUpperDeepenRight": cast 64;
			case "mouthUpperDeepenLeft": cast 65;
			case "mouthUpperRight": cast 66;
			case "mouthUpperLeft": cast 67;
			case "mouthLowerRight": cast 68;
			case "mouthLowerLeft": cast 69;
			case "mouthCornerPullRight": cast 70;
			case "mouthCornerPullLeft": cast 71;
			case "mouthCornerSlantRight": cast 72;
			case "mouthCornerSlantLeft": cast 73;
			case "mouthFrownRight": cast 74;
			case "mouthFrownLeft": cast 75;
			case "mouthStretchRight": cast 76;
			case "mouthStretchLeft": cast 77;
			case "mouthDimpleRight": cast 78;
			case "mouthDimpleLeft": cast 79;
			case "mouthRaiserUpper": cast 80;
			case "mouthRaiserLower": cast 81;
			case "mouthPressRight": cast 82;
			case "mouthPressLeft": cast 83;
			case "mouthTightenerRight": cast 84;
			case "mouthTightenerLeft": cast 85;
			case "tongueOut": cast 86;
			case "tongueUp": cast 87;
			case "tongueDown": cast 88;
			case "tongueRight": cast 89;
			case "tongueLeft": cast 90;
			case "tongueRoll": cast 91;
			case "tongueBlendDown": cast 92;
			case "tongueCurlUp": cast 93;
			case "tongueSquish": cast 94;
			case "tongueFlat": cast 95;
			case "tongueTwistRight": cast 96;
			case "tongueTwistLeft": cast 97;
			case "softPalateClose": cast 98;
			case "throatSwallow": cast 99;
			case "neckFlexRight": cast 100;
			case "neckFlexLeft": cast 101;
			case "eyeClosed": cast 102;
			case "eyeWide": cast 103;
			case "eyeSquint": cast 104;
			case "eyeDilation": cast 105;
			case "eyeConstrict": cast 106;
			case "browDownRight": cast 107;
			case "browDownLeft": cast 108;
			case "browDown": cast 109;
			case "browUpRight": cast 110;
			case "browUpLeft": cast 111;
			case "browUp": cast 112;
			case "noseSneer": cast 113;
			case "nasalDilation": cast 114;
			case "nasalConstrict": cast 115;
			case "cheekPuff": cast 116;
			case "cheekSuck": cast 117;
			case "cheekSquint": cast 118;
			case "lipSuckUpper": cast 119;
			case "lipSuckLower": cast 120;
			case "lipSuck": cast 121;
			case "lipFunnelUpper": cast 122;
			case "lipFunnelLower": cast 123;
			case "lipFunnel": cast 124;
			case "lipPuckerUpper": cast 125;
			case "lipPuckerLower": cast 126;
			case "lipPucker": cast 127;
			case "mouthUpperUp": cast 128;
			case "mouthLowerDown": cast 129;
			case "mouthOpen": cast 130;
			case "mouthRight": cast 131;
			case "mouthLeft": cast 132;
			case "mouthSmileRight": cast 133;
			case "mouthSmileLeft": cast 134;
			case "mouthSmile": cast 135;
			case "mouthSadRight": cast 136;
			case "mouthSadLeft": cast 137;
			case "mouthSad": cast 138;
			case "mouthStretch": cast 139;
			case "mouthDimple": cast 140;
			case "mouthTightener": cast 141;
			case "mouthPress": cast 142;
			case "max": cast 143;
			case _: null;
		}
	}
}
