package sunaba;

enum abstract Error(Int) from Int to Int {
	var ok = cast 0;
	var failed = cast 1;
	var unavailable = cast 2;
	var unconfigured = cast 3;
	var unauthorized = cast 4;
	var parameterRangeError = cast 5;
	var outOfMemory = cast 6;
	var fileNotFound = cast 7;
	var fileBadDrive = cast 8;
	var fileBadPath = cast 9;
	var fileNoPermission = cast 10;
	var fileAlreadyInUse = cast 11;
	var fileCantOpen = cast 12;
	var fileCantWrite = cast 13;
	var fileCantRead = cast 14;
	var fileUnrecognized = cast 15;
	var fileCorrupt = cast 16;
	var fileMissingDependencies = cast 17;
	var fileEof = cast 18;
	var cantOpen = cast 19;
	var cantCreate = cast 20;
	var queryFailed = cast 21;
	var alreadyInUse = cast 22;
	var locked = cast 23;
	var timeout = cast 24;
	var cantConnect = cast 25;
	var cantResolve = cast 26;
	var connectionError = cast 27;
	var cantAcquireResource = cast 28;
	var cantFork = cast 29;
	var invalidData = cast 30;
	var invalidParameter = cast 31;
	var alreadyExists = cast 32;
	var doesNotExist = cast 33;
	var databaseCantRead = cast 34;
	var databaseCantWrite = cast 35;
	var compilationFailed = cast 36;
	var methodNotFound = cast 37;
	var linkFailed = cast 38;
	var scriptFailed = cast 39;
	var cyclicLink = cast 40;
	var invalidDeclaration = cast 41;
	var duplicateSymbol = cast 42;
	var parseError = cast 43;
	var busy = cast 44;
	var skip = cast 45;
	var help = cast 46;
	var bug = cast 47;
	var printerOnFire = cast 48;
	public static var values = [ok, failed, unavailable, unconfigured, unauthorized, parameterRangeError, outOfMemory, fileNotFound, fileBadDrive, fileBadPath, fileNoPermission, fileAlreadyInUse, fileCantOpen, fileCantWrite, fileCantRead, fileUnrecognized, fileCorrupt, fileMissingDependencies, fileEof, cantOpen, cantCreate, queryFailed, alreadyInUse, locked, timeout, cantConnect, cantResolve, connectionError, cantAcquireResource, cantFork, invalidData, invalidParameter, alreadyExists, doesNotExist, databaseCantRead, databaseCantWrite, compilationFailed, methodNotFound, linkFailed, scriptFailed, cyclicLink, invalidDeclaration, duplicateSymbol, parseError, busy, skip, help, bug, printerOnFire];

	public static function fromString(s:String):Null<Int> {
		return switch (s) {
			case "ok": cast 0;
			case "failed": cast 1;
			case "unavailable": cast 2;
			case "unconfigured": cast 3;
			case "unauthorized": cast 4;
			case "parameterRangeError": cast 5;
			case "outOfMemory": cast 6;
			case "fileNotFound": cast 7;
			case "fileBadDrive": cast 8;
			case "fileBadPath": cast 9;
			case "fileNoPermission": cast 10;
			case "fileAlreadyInUse": cast 11;
			case "fileCantOpen": cast 12;
			case "fileCantWrite": cast 13;
			case "fileCantRead": cast 14;
			case "fileUnrecognized": cast 15;
			case "fileCorrupt": cast 16;
			case "fileMissingDependencies": cast 17;
			case "fileEof": cast 18;
			case "cantOpen": cast 19;
			case "cantCreate": cast 20;
			case "queryFailed": cast 21;
			case "alreadyInUse": cast 22;
			case "locked": cast 23;
			case "timeout": cast 24;
			case "cantConnect": cast 25;
			case "cantResolve": cast 26;
			case "connectionError": cast 27;
			case "cantAcquireResource": cast 28;
			case "cantFork": cast 29;
			case "invalidData": cast 30;
			case "invalidParameter": cast 31;
			case "alreadyExists": cast 32;
			case "doesNotExist": cast 33;
			case "databaseCantRead": cast 34;
			case "databaseCantWrite": cast 35;
			case "compilationFailed": cast 36;
			case "methodNotFound": cast 37;
			case "linkFailed": cast 38;
			case "scriptFailed": cast 39;
			case "cyclicLink": cast 40;
			case "invalidDeclaration": cast 41;
			case "duplicateSymbol": cast 42;
			case "parseError": cast 43;
			case "busy": cast 44;
			case "skip": cast 45;
			case "help": cast 46;
			case "bug": cast 47;
			case "printerOnFire": cast 48;
			case _: null;
		}
	}
}
