package newhaven;

enum abstract Joint(Int) from Int to Int {
	var root = cast 0;
	var hips = cast 1;
	var spine = cast 2;
	var chest = cast 3;
	var upperChest = cast 4;
	var neck = cast 5;
	var head = cast 6;
	var headTip = cast 7;
	var leftShoulder = cast 8;
	var leftUpperArm = cast 9;
	var leftLowerArm = cast 10;
	var rightShoulder = cast 11;
	var rightUpperArm = cast 12;
	var rightLowerArm = cast 13;
	var leftUpperLeg = cast 14;
	var leftLowerLeg = cast 15;
	var leftFoot = cast 16;
	var leftToes = cast 17;
	var rightUpperLeg = cast 18;
	var rightLowerLeg = cast 19;
	var rightFoot = cast 20;
	var rightToes = cast 21;
	var leftHand = cast 22;
	var leftPalm = cast 23;
	var leftWrist = cast 24;
	var leftThumbMetacarpal = cast 25;
	var leftThumbPhalanxProximal = cast 26;
	var leftThumbPhalanxDistal = cast 27;
	var leftThumbTip = cast 28;
	var leftIndexFingerMetacarpal = cast 29;
	var leftIndexFingerPhalanxProximal = cast 30;
	var leftIndexFingerPhalanxIntermediate = cast 31;
	var leftIndexFingerPhalanxDistal = cast 32;
	var leftIndexFingerTip = cast 33;
	var leftMiddleFingerMetacarpal = cast 34;
	var leftMiddleFingerPhalanxProximal = cast 35;
	var leftMiddleFingerPhalanxIntermediate = cast 36;
	var leftMiddleFingerPhalanxDistal = cast 37;
	var leftMiddleFingerTip = cast 38;
	var leftRingFingerMetacarpal = cast 39;
	var leftRingFingerPhalanxProximal = cast 40;
	var leftRingFingerPhalanxIntermediate = cast 41;
	var leftRingFingerPhalanxDistal = cast 42;
	var leftRingFingerTip = cast 43;
	var leftPinkyFingerMetacarpal = cast 44;
	var leftPinkyFingerPhalanxProximal = cast 45;
	var leftPinkyFingerPhalanxIntermediate = cast 46;
	var leftPinkyFingerPhalanxDistal = cast 47;
	var leftPinkyFingerTip = cast 48;
	var rightHand = cast 49;
	var rightPalm = cast 50;
	var rightWrist = cast 51;
	var rightThumbMetacarpal = cast 52;
	var rightThumbPhalanxProximal = cast 53;
	var rightThumbPhalanxDistal = cast 54;
	var rightThumbTip = cast 55;
	var rightIndexFingerMetacarpal = cast 56;
	var rightIndexFingerPhalanxProximal = cast 57;
	var rightIndexFingerPhalanxIntermediate = cast 58;
	var rightIndexFingerPhalanxDistal = cast 59;
	var rightIndexFingerTip = cast 60;
	var rightMiddleFingerMetacarpal = cast 61;
	var rightMiddleFingerPhalanxProximal = cast 62;
	var rightMiddleFingerPhalanxIntermediate = cast 63;
	var rightMiddleFingerPhalanxDistal = cast 64;
	var rightMiddleFingerTip = cast 65;
	var rightRingFingerMetacarpal = cast 66;
	var rightRingFingerPhalanxProximal = cast 67;
	var rightRingFingerPhalanxIntermediate = cast 68;
	var rightRingFingerPhalanxDistal = cast 69;
	var rightRingFingerTip = cast 70;
	var rightPinkyFingerMetacarpal = cast 71;
	var rightPinkyFingerPhalanxProximal = cast 72;
	var rightPinkyFingerPhalanxIntermediate = cast 73;
	var rightPinkyFingerPhalanxDistal = cast 74;
	var rightPinkyFingerTip = cast 75;
	var lowerChest = cast 76;
	var leftScapula = cast 77;
	var leftWristTwist = cast 78;
	var rightScapula = cast 79;
	var rightWristTwist = cast 80;
	var leftFootTwist = cast 81;
	var leftHeel = cast 82;
	var leftMiddleFoot = cast 83;
	var rightFootTwist = cast 84;
	var rightHeel = cast 85;
	var rightMiddleFoot = cast 86;
	var max = cast 87;
	public static var values = [root, hips, spine, chest, upperChest, neck, head, headTip, leftShoulder, leftUpperArm, leftLowerArm, rightShoulder, rightUpperArm, rightLowerArm, leftUpperLeg, leftLowerLeg, leftFoot, leftToes, rightUpperLeg, rightLowerLeg, rightFoot, rightToes, leftHand, leftPalm, leftWrist, leftThumbMetacarpal, leftThumbPhalanxProximal, leftThumbPhalanxDistal, leftThumbTip, leftIndexFingerMetacarpal, leftIndexFingerPhalanxProximal, leftIndexFingerPhalanxIntermediate, leftIndexFingerPhalanxDistal, leftIndexFingerTip, leftMiddleFingerMetacarpal, leftMiddleFingerPhalanxProximal, leftMiddleFingerPhalanxIntermediate, leftMiddleFingerPhalanxDistal, leftMiddleFingerTip, leftRingFingerMetacarpal, leftRingFingerPhalanxProximal, leftRingFingerPhalanxIntermediate, leftRingFingerPhalanxDistal, leftRingFingerTip, leftPinkyFingerMetacarpal, leftPinkyFingerPhalanxProximal, leftPinkyFingerPhalanxIntermediate, leftPinkyFingerPhalanxDistal, leftPinkyFingerTip, rightHand, rightPalm, rightWrist, rightThumbMetacarpal, rightThumbPhalanxProximal, rightThumbPhalanxDistal, rightThumbTip, rightIndexFingerMetacarpal, rightIndexFingerPhalanxProximal, rightIndexFingerPhalanxIntermediate, rightIndexFingerPhalanxDistal, rightIndexFingerTip, rightMiddleFingerMetacarpal, rightMiddleFingerPhalanxProximal, rightMiddleFingerPhalanxIntermediate, rightMiddleFingerPhalanxDistal, rightMiddleFingerTip, rightRingFingerMetacarpal, rightRingFingerPhalanxProximal, rightRingFingerPhalanxIntermediate, rightRingFingerPhalanxDistal, rightRingFingerTip, rightPinkyFingerMetacarpal, rightPinkyFingerPhalanxProximal, rightPinkyFingerPhalanxIntermediate, rightPinkyFingerPhalanxDistal, rightPinkyFingerTip, lowerChest, leftScapula, leftWristTwist, rightScapula, rightWristTwist, leftFootTwist, leftHeel, leftMiddleFoot, rightFootTwist, rightHeel, rightMiddleFoot, max];

	public static function fromString(s:String):Null<Int> {
		return switch (s) {
			case "root": cast 0;
			case "hips": cast 1;
			case "spine": cast 2;
			case "chest": cast 3;
			case "upperChest": cast 4;
			case "neck": cast 5;
			case "head": cast 6;
			case "headTip": cast 7;
			case "leftShoulder": cast 8;
			case "leftUpperArm": cast 9;
			case "leftLowerArm": cast 10;
			case "rightShoulder": cast 11;
			case "rightUpperArm": cast 12;
			case "rightLowerArm": cast 13;
			case "leftUpperLeg": cast 14;
			case "leftLowerLeg": cast 15;
			case "leftFoot": cast 16;
			case "leftToes": cast 17;
			case "rightUpperLeg": cast 18;
			case "rightLowerLeg": cast 19;
			case "rightFoot": cast 20;
			case "rightToes": cast 21;
			case "leftHand": cast 22;
			case "leftPalm": cast 23;
			case "leftWrist": cast 24;
			case "leftThumbMetacarpal": cast 25;
			case "leftThumbPhalanxProximal": cast 26;
			case "leftThumbPhalanxDistal": cast 27;
			case "leftThumbTip": cast 28;
			case "leftIndexFingerMetacarpal": cast 29;
			case "leftIndexFingerPhalanxProximal": cast 30;
			case "leftIndexFingerPhalanxIntermediate": cast 31;
			case "leftIndexFingerPhalanxDistal": cast 32;
			case "leftIndexFingerTip": cast 33;
			case "leftMiddleFingerMetacarpal": cast 34;
			case "leftMiddleFingerPhalanxProximal": cast 35;
			case "leftMiddleFingerPhalanxIntermediate": cast 36;
			case "leftMiddleFingerPhalanxDistal": cast 37;
			case "leftMiddleFingerTip": cast 38;
			case "leftRingFingerMetacarpal": cast 39;
			case "leftRingFingerPhalanxProximal": cast 40;
			case "leftRingFingerPhalanxIntermediate": cast 41;
			case "leftRingFingerPhalanxDistal": cast 42;
			case "leftRingFingerTip": cast 43;
			case "leftPinkyFingerMetacarpal": cast 44;
			case "leftPinkyFingerPhalanxProximal": cast 45;
			case "leftPinkyFingerPhalanxIntermediate": cast 46;
			case "leftPinkyFingerPhalanxDistal": cast 47;
			case "leftPinkyFingerTip": cast 48;
			case "rightHand": cast 49;
			case "rightPalm": cast 50;
			case "rightWrist": cast 51;
			case "rightThumbMetacarpal": cast 52;
			case "rightThumbPhalanxProximal": cast 53;
			case "rightThumbPhalanxDistal": cast 54;
			case "rightThumbTip": cast 55;
			case "rightIndexFingerMetacarpal": cast 56;
			case "rightIndexFingerPhalanxProximal": cast 57;
			case "rightIndexFingerPhalanxIntermediate": cast 58;
			case "rightIndexFingerPhalanxDistal": cast 59;
			case "rightIndexFingerTip": cast 60;
			case "rightMiddleFingerMetacarpal": cast 61;
			case "rightMiddleFingerPhalanxProximal": cast 62;
			case "rightMiddleFingerPhalanxIntermediate": cast 63;
			case "rightMiddleFingerPhalanxDistal": cast 64;
			case "rightMiddleFingerTip": cast 65;
			case "rightRingFingerMetacarpal": cast 66;
			case "rightRingFingerPhalanxProximal": cast 67;
			case "rightRingFingerPhalanxIntermediate": cast 68;
			case "rightRingFingerPhalanxDistal": cast 69;
			case "rightRingFingerTip": cast 70;
			case "rightPinkyFingerMetacarpal": cast 71;
			case "rightPinkyFingerPhalanxProximal": cast 72;
			case "rightPinkyFingerPhalanxIntermediate": cast 73;
			case "rightPinkyFingerPhalanxDistal": cast 74;
			case "rightPinkyFingerTip": cast 75;
			case "lowerChest": cast 76;
			case "leftScapula": cast 77;
			case "leftWristTwist": cast 78;
			case "rightScapula": cast 79;
			case "rightWristTwist": cast 80;
			case "leftFootTwist": cast 81;
			case "leftHeel": cast 82;
			case "leftMiddleFoot": cast 83;
			case "rightFootTwist": cast 84;
			case "rightHeel": cast 85;
			case "rightMiddleFoot": cast 86;
			case "max": cast 87;
			case _: null;
		}
	}
}
