package newhaven;

enum abstract PropertyHint(Int) from Int to Int {
	var none = cast 0;
	var range = cast 1;
	var _enum = cast 2;
	var enumSuggestion = cast 3;
	var expEasing = cast 4;
	var link = cast 5;
	var flags = cast 6;
	var layers2dRender = cast 7;
	var layers2dPhysics = cast 8;
	var layers2dNavigation = cast 9;
	var layers3dRender = cast 10;
	var layers3dPhysics = cast 11;
	var layers3dNavigation = cast 12;
	var file = cast 13;
	var dir = cast 14;
	var globalFile = cast 15;
	var globalDir = cast 16;
	var resourceType = cast 17;
	var multilineText = cast 18;
	var expression = cast 19;
	var placeholderText = cast 20;
	var colorNoAlpha = cast 21;
	var objectId = cast 22;
	var typeString = cast 23;
	var nodePathToEditedNode = cast 24;
	var objectTooBig = cast 25;
	var nodePathValidTypes = cast 26;
	var saveFile = cast 27;
	var globalSaveFile = cast 28;
	var intIsObjectid = cast 29;
	var intIsPointer = cast 30;
	var arrayType = cast 31;
	var localeId = cast 32;
	var localizableString = cast 33;
	var nodeType = cast 34;
	var hideQuaternionEdit = cast 35;
	var password = cast 36;
	var layersAvoidance = cast 37;
	var dictionaryType = cast 38;
	var toolButton = cast 39;
	var oneshot = cast 40;
	var groupEnable = cast 42;
	var inputName = cast 43;
	var filePath = cast 44;
	var max = cast 45;
	public static var values = [none, range, _enum, enumSuggestion, expEasing, link, flags, layers2dRender, layers2dPhysics, layers2dNavigation, layers3dRender, layers3dPhysics, layers3dNavigation, file, dir, globalFile, globalDir, resourceType, multilineText, expression, placeholderText, colorNoAlpha, objectId, typeString, nodePathToEditedNode, objectTooBig, nodePathValidTypes, saveFile, globalSaveFile, intIsObjectid, intIsPointer, arrayType, localeId, localizableString, nodeType, hideQuaternionEdit, password, layersAvoidance, dictionaryType, toolButton, oneshot, groupEnable, inputName, filePath, max];

	public static function fromString(s:String):Null<Int> {
		return switch (s) {
			case "none": cast 0;
			case "range": cast 1;
			case "_enum": cast 2;
			case "enumSuggestion": cast 3;
			case "expEasing": cast 4;
			case "link": cast 5;
			case "flags": cast 6;
			case "layers2dRender": cast 7;
			case "layers2dPhysics": cast 8;
			case "layers2dNavigation": cast 9;
			case "layers3dRender": cast 10;
			case "layers3dPhysics": cast 11;
			case "layers3dNavigation": cast 12;
			case "file": cast 13;
			case "dir": cast 14;
			case "globalFile": cast 15;
			case "globalDir": cast 16;
			case "resourceType": cast 17;
			case "multilineText": cast 18;
			case "expression": cast 19;
			case "placeholderText": cast 20;
			case "colorNoAlpha": cast 21;
			case "objectId": cast 22;
			case "typeString": cast 23;
			case "nodePathToEditedNode": cast 24;
			case "objectTooBig": cast 25;
			case "nodePathValidTypes": cast 26;
			case "saveFile": cast 27;
			case "globalSaveFile": cast 28;
			case "intIsObjectid": cast 29;
			case "intIsPointer": cast 30;
			case "arrayType": cast 31;
			case "localeId": cast 32;
			case "localizableString": cast 33;
			case "nodeType": cast 34;
			case "hideQuaternionEdit": cast 35;
			case "password": cast 36;
			case "layersAvoidance": cast 37;
			case "dictionaryType": cast 38;
			case "toolButton": cast 39;
			case "oneshot": cast 40;
			case "groupEnable": cast 42;
			case "inputName": cast 43;
			case "filePath": cast 44;
			case "max": cast 45;
			case _: null;
		}
	}
}
